### ISSUE TITLE
Webhook notifications come in 3 times on HA setup

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-gitlab#403] opened 2023-09-11 13:38 UTC
On the community server, which has a 3 node cluster of MM app servers running, I'm getting 3 DM notifications for every operation that sends a notification.

![image](https://github.com/mattermost/mattermost-plugin-gitlab/assets/6913320/17811126-231a-4af6-8768-9d709cba0052)

**Comment by raghavaggarwal2308** [comment] 2023-09-18 10:41
@mickmister Can you please specify the plugin and MM version you are using here?

**Comment by mickmister** [comment] 2023-09-18 13:10
@raghavaggarwal2308
GitLab plugin 1.7.0
MM latest master, as of submitting the issue

**Comment by raghavaggarwal2308** [comment] 2023-09-25 07:42
@mickmister Can you please provide us an environment where this issue is getting reproduced?

**Comment by mickmister** [comment] 2023-09-27 13:54
@raghavaggarwal2308 This is happening on the community server. I'm not sure of any specific reproduction steps. I know we are running a 3 node MM cluster, but I wouldn't expect that to generate 3 posts, since the webhook request only gets handled by one node.

@spirosoik @phoinixgrr I'm curious if you are experiencing this same issue with DM notifications from the GitLab bot

**Comment by phoinixgrr** [comment] 2023-09-27 13:55
@mickmister No issues from my side. Getting a single notification.

**Comment by mickmister** [comment] 2023-09-27 13:57
This last occurred for me on 2023-9-11, though that's the only day in a while that I received a notification from the GitLab bot other than the daily reminder

**Comment by spirosoik** [comment] 2023-09-27 14:03
> @raghavaggarwal2308 This is happening on the community server. I'm not sure of any specific reproduction steps. I know we are running a 3 node MM cluster, but I wouldn't expect that to generate 3 posts, since the webhook request only gets handled by one node.
> 
> @spirosoik @phoinixgrr I'm curious if you are experiencing this same issue with DM notifications from the GitLab bot

yes I have the same issue @mickmister . 3 posts are coming for me. I did a disconnect and removed any redundant subscriptions just to be sure. Though still the same issue.

**Comment by phoinixgrr** [comment] 2023-09-27 14:05
🤷  How is this possible? Is there a specific kind of GitLab notifications getting affected?

**Comment by phoinixgrr** [comment] 2023-09-29 11:37
Confirmed, On this kind of notifications I get multiple: 

<img width="817" alt="Screenshot 2023-09-29 at 14 36 53" src="https://github.com/mattermost/mattermost-plugin-gitlab/assets/36594156/b00049cb-39d8-47a4-935e-89e793713d95">

**Comment by mickmister** [comment] 2023-09-29 14:28
@spirosoik Any ideas on what we can do to debug this, on the SRE level? i.e. Can we verify there is exactly one request coming in per GitLab user interaction? We haven't seen any similar behavior from other plugins that use webhooks, so the two potential sources of issues seem to be:

- Multiple requests coming in
- The GitLab plugin is creating multiple/duplicate posts from one incoming request

It very well could be the case that the GitLab plugin is creating duplicate posts, though I would like to rule out the first theory of multiple webhook requests coming in from GitLab. @raghavaggarwal2308 What are your thoughts based on our discussion?

**Comment by spirosoik** [comment] 2023-10-02 05:13
@mickmister feel free to start a thread in SRE channel and the team will act accordingly.

**Comment by raghavaggarwal2308** [comment] 2023-10-05 11:59
@mickmister Till now I am unable to reproduce this issue on my side. But I doubt that the plugin code will create multiple posts as I have seen the code and I can't see anything that might get affected by the multi-node environment. The only reason that can cause the issue is that there are multiple subscriptions with the same event in a single channel, but I think @spirosoik has already tested that it's not the case.
Also, I have verified that Gitlab is sending only a single webhook request.

**Comment by raghavaggarwal2308** [comment] 2024-07-16 12:45
@phoinixgrr @spirosoik Are you still facing this issue or we can close it?

**Comment by phoinixgrr** [comment] 2024-07-17 16:22
> @phoinixgrr @spirosoik Are you still facing this issue or we can close it?

Cannot say. Haven't been using the gitlab plugin for sometime now.

**Comment by raghavaggarwal2308** [comment] 2024-07-17 18:43
Closing for now, can reopen if someone faces the issue in future.

**Closed by raghavaggarwal2308** 2024-07-17 18:43 UTC
