### ISSUE TITLE
sidebar buttons still use gitlab.com as base url

### ISSUE THREAD

**Issue by bkarlson** [mattermost/mattermost-plugin-gitlab#129] opened 2020-01-06 03:48 UTC
Mattermost Version: 5.17.1

After successfully configuring and enabling the plugin, I can see sidebar buttons with correct notification numbers, but leading to gitlab.com instead of our company gitlab instance URL. 

In settings URL is set correctly (otherwise plugin won't be able to connect to our gitlab), but sidebar buttons seem to ignore this setting.

**Comment by manland** [comment] 2020-01-06 08:34
@bkarlson thanks to have taken time to open this issue ;)

This is a duplicate of #74 which is already fixed (but not deployed). If you return on your mattermost url and make a refresh (F5) you should see good url ;)

Please feel free to reopen or to open another issue in case it's not working.

**Closed by manland** 2020-01-06 08:34 UTC
