### ISSUE TITLE
Base url not use ?

### ISSUE THREAD

**Issue by MehdiNabi8000** [mattermost/mattermost-plugin-gitlab#109] opened 2019-10-10 14:08 UTC
Hi,

I use gitlab 12.3.5-ee and integrated mattermost on my own server.

I set up the plugin using the install guide on my on prem gitlab application, and I am always sent to gitlab.com when clicking any button or typing commands. 

The only commands that is run on my gitlab instance is /gitlab connect, but then all the buttons or commands send me to gitlab.com instead of my https://gitlab.xxxxxx.com

For example, I copy/paste the url for the MR :
https://gitlab.com/dashboard/merge_requests?state=opened&author_username=xxx

should be 
https://gitlab.xxxxxx.com/dashboard/merge_requests?state=opened&author_username=xxx

I am relatively confident on my configuration and I do not think I have miss something. The only thing I am not sure of is the profile/applications part, as the "authorization callback URL" does not exists, so I fille the field "Redirect URI" with  "https://your-mattermost-url.com/plugins/com.github.manland.mattermost-plugin-gitlab/oauth/complete"  (of course replacing the your-mattermost-url.com with mine)

**Comment by MehdiNabi8000** [comment] 2019-10-15 08:25
Hi, I tried again today using the icon in mattermost, and I am redirected to the right gitlab instance. 

I guess cookies or web session stuff were involved. I did not change the configuration. I will not close the issue but feel free to do it :)

**Comment by hanzei** [comment] 2019-10-15 09:43
This is a duplicate of https://github.com/mattermost/mattermost-plugin-gitlab/issues/74

**Closed** 2019-10-15 09:43 UTC
Labels: Duplicate
