### ISSUE TITLE
multiple GitLab instances

### ISSUE THREAD

**Issue by swills** [mattermost/mattermost-plugin-gitlab#242] opened 2021-02-02 02:04 UTC
Is there a way to connect to multiple GitLab instances? I use both a personal one and the gitlab.com one and would like to connect the plugin to both.

**Comment by iomodo** [comment] 2021-02-02 06:51
There is no way yet.

**Comment by hanzei** [comment] 2021-02-08 19:52
Duplicate of

**Closed** 2021-02-08 19:52 UTC
Labels: Difficulty/3:Hard, Duplicate, Needs Spec, Type/Enhancement

**Comment by cforce** [comment] 2022-07-14 08:54
Is this feature request rejected, or why are all related tickets closed?
Confused about Duplicate of https://github.com/mattermost/mattermost-plugin-gitlab/issues/242, which is the same issue!?

**Comment by hanzei** [comment] 2022-09-18 06:29
Good catch. 

The correct ticket to link is #35
