### ISSUE TITLE
Subscribe to repository with subnamespace

### ISSUE THREAD

**Issue by CarlDemus** [mattermost/mattermost-plugin-gitlab#99] opened 2019-09-19 10:02 UTC
Hello, 
we using this plugin at our company, we encounter a problem with one of our repository.
This repository have a particularity, it contain a subnamespace.

`/gitlab subscribe owner/repo/subnamespace `return and error : invalid group

**Comment by manland** [comment] 2019-09-20 08:57
@CarlDemus `subnamespace` is like `group`?

Could be a duplicate of https://github.com/mattermost/mattermost-plugin-gitlab/issues/65?

**Comment by CarlDemus** [comment] 2019-09-20 16:31
Maybe

**Comment by levb** [comment] 2019-10-01 12:55
It does appear a duplicate of #65, closing in favor of it.

**Closed by levb** 2019-10-01 12:55 UTC
Labels: Enhancement, Triage
