### ISSUE TITLE
Issue count in sidebar header is wrong

### ISSUE THREAD

**Issue by bk138** [mattermost/mattermost-plugin-gitlab#158] opened 2020-04-21 14:41 UTC
I have searched the other issues, but could not find an answer.

The sidebar header of our local MM instance shows 20 open issues for my user, but in reality on our local gitlab I have some 39 issues open. Is this a display limit of the sidebar?

Please let me know how to debug the situation, willing to help here :-)

**Comment by SilverOnion** [comment] 2020-07-30 16:53
We are also running into this issue. I see 20 issues only.

In addition, after adding another to-do (now at 3) and after preforming a refresh I still see 2.

**Comment by sibasankarnayak** [comment] 2022-04-03 14:47
@hanzei @mickmister i see this is a issue duplicate of this issue #237

**Closed** 2022-04-03 22:46 UTC
Labels: Duplicate
