### ISSUE TITLE
Plugin is hitting burst limit on go-gitlab client

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-gitlab#291] opened 2022-04-13 14:36 UTC
The task here is to investigate why we might be hitting the burst limit specified by the `go-gitlab` client. Each MM user should have its own rate limit, but it seems the `go-gitlab` library may be limiting the plugin overall across all user tokens.

The limits set by GitLab are quite generous, so I don't think we're hitting their actual API limits
https://docs.gitlab.com/ee/user/admin_area/settings/user_and_ip_rate_limits.html#enable-authenticated-api-request-rate-limit

More context here https://community-daily.mattermost.com/core/pl/hi4crhf483ybpyuktou8acu7go

**Comment by mickmister** [comment] 2022-04-13 14:44
@sibasankarnayak This is causing issues with log spam on a customer's server, as seen in the linked thread in the description. I'm thinking we have a few options here:

- Pinpoint how we can properly use the `go-gitlab` to take into account our use case of hitting the API in quick succession to populate data in the LHS for each user. This would be the ideal situation.
- Provide a config variable to disable this feature, so the log spam does not occur. This solution removes a feature, which is not ideal.

**Comment by raghavaggarwal2308** [comment] 2023-10-23 14:53
@mickmister I was able to reproduce this issue by configuring a custom limiter(with rate limit "1" and burst limit to "0") in the `go-gitlab` package using the ["WithCustomLimiter"](https://pkg.go.dev/github.com/xanzy/go-gitlab#WithCustomLimiter) function. By default, the package takes the limit and burst value from the [Gitlab Configuration](https://gitlab.com/help/instance_configuration) of the user. According to my understanding of the package code, if the rate limit of Gitlab is configured to be less than "60" requests per minute (For example 50) and the user makes 3600 requests per minute (i.e. 60 requests per second) then the user will get a response for the first 50 requests every second and the error for the remaining 10 requests. Because in that case, the rate limit will have some specific value and the burst limit will have zero value ([Code reference](https://github.com/xanzy/go-gitlab/blob/ef50bf1b77702ce77c1ca7fbbb02381188e38a57/gitlab.go#L473-L501)). Is it possible to confirm this value (i.e. "Authenticated API requests") for the user who is facing the issue?

**Comment by mickmister** [comment] 2023-10-24 04:59
> By default, the package takes the limit and burst value from the [Gitlab Configuration](https://gitlab.com/help/instance_configuration) of the user.

Is the limit per user or per GitLab instance? Also the fact that we create a new client for each request, and were fanning out the requests for "unreads", "myprs" etc. is probably contributing to this issue.

@raghavaggarwal2308 Based on your research, I'm not sure if there is anything that should be done here. The only thing that comes to mind is that there's currently no way for the plugin to know how many requests it's sending to GitLab's API, whether it's because we create multiple clients, or we potentially run more than one instance of the plugin simultaneously.

> Is it possible to confirm this value (i.e. "Authenticated API requests") for the user who is facing the issue?

The thread linked in the issue description contains a conversation with the admin that was experiencing this. This was quite a while ago though so I'm not sure if they are still available to discuss.

Thanks for looking so deeply into this. What are your thoughts based on the above?

**Comment by raghavaggarwal2308** [comment] 2023-10-24 10:46
@mickmister Apologies from my side. I have updated the example in my previous comment a little bit.

> Is the limit per user or per GitLab instance? Also, the fact that we create a new client for each request, and were fanning out the requests for "unreads", "myprs" etc. is probably contributing to this issue.

The [limit is per user](https://docs.gitlab.com/ee/user/gitlab_com/index.html#gitlabcom-specific-rate-limits). As I mentioned in the comment before if the limit is less than 60 on Gitlab then the "go-gitlab" package will configure the limit to be <1 request per second and we are making 4 requests (unreads, reviews, prs, and assignments) at a time per user. So, I think that might be causing the issue.

> @raghavaggarwal2308 Based on your research, I'm not sure if there is anything that should be done here. The only thing that comes to mind is that there's currently no way for the plugin to know how many requests it's sending to GitLab's API, whether it's because we create multiple clients, or we potentially run more than one instance of the plugin simultaneously.

I agree with this. I don't think there is any way for us right now to count the number of requests being sent to GitLab.

I think the only thing we can do here is to ask the user to configure the rate limit on Gitlab according to our discussion (i.e. >60).

**Comment by raghavaggarwal2308** [comment] 2024-01-04 09:55
@mickmister Is there anything to do on this issue for us or can we close it?

**Closed** 2024-01-05 18:27 UTC
