### ISSUE TITLE
New tag message is shown when a tag is deleted

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-gitlab#232] opened 2020-11-19 10:39 UTC
It writes "New tag" also when I delete a tag.

Output looks like this when I push a new tag and when i push --delete a tag: https://paste.ee/p/xwvbQ

_Issue created from a [Mattermost message](https://community.mattermost.com/_redirect/pl/nx9trgtiufb18xqh5bnnnkbc3w) *by `@martbhell`*._

**Comment by martbhell** [comment] 2020-11-19 10:47
For posterity:

Commands used:
```
$ git tag -s v1.0.4 
$ git push origin v1.0.04
$ git push --delete v1.0.4
```

Content of the pastee:
```
08:19
johan/dotfiles New tag v1.0.4 by Johan Guldmyr: 4
-----BEGIN PGP SIGNATURE-----
MYSIG
-----END PGP SIGNATURE-----

08:19
johan/dotfiles New tag v1.0.4 by Johan Guldmyr: 4
-----BEGIN PGP SIGNATURE-----

MYSIG

-----END PGP SIGNATURE-----

08:20
johan/dotfiles New tag v1.0.4 by Johan Guldmyr:

08:20
johan/dotfiles New tag v1.0.4 by Johan Guldmyr:
~                                                   
```

**Comment by Quaqmre** [comment] 2021-01-30 18:50
I would like to work on it.

**Comment by hanzei** [comment] 2021-02-08 11:40
Awesome, thanks @Quaqmre :+1:

**Comment by Quaqmre** [comment] 2021-02-14 21:13
Hi guys , I was working on this issue then I find some  that ,It is not related webhoos or Mattermost api , when u try to delete tag remotely like ' git push  --delete anytag' that is deleted gitlab remoot repo but *anytag* still there in your local repo. And when u try to push or delete any tag git add the *anytag" again.Then u saw 2 message on your channel 1 message about deleted mesage the other one is brendnew tag with the same name deleted one. Because u have the deleted tag in your local repo.When u delete tags remotely u have to delete in your local repo.

I will upload screenshot tomorrow morning :)

**Comment by hanzei** [comment] 2021-02-15 09:00
@jsmestad In order to delete a tag locally and remotely, you have to also run `git tag -d anytag`.

**Comment by Quaqmre** [comment] 2021-02-15 10:09
![commandAndWebbHook](https://user-images.githubusercontent.com/44048737/107932763-f9af8180-6f8e-11eb-9710-0d021d175552.png)

**Comment by hanzei** [comment] 2021-02-15 10:12
That seems like the expected behavior to me. `git push` will publish `v4` again, given that it was not deleted locally.

**Comment by Quaqmre** [comment] 2021-02-19 12:38
@hanzei How should we proceed about this task ? Can you help me what should i do ?

**Comment by hanzei** [comment] 2021-02-19 12:47
@Quaqmre The example looks good to me. The notifications appear in the right order. Would you please create a WIP PR for an early code review?

**Comment by Quaqmre** [comment] 2021-02-27 18:08
@hanzei Actually I dont know how can I create WIP PR , I try to create PR but I dont have any commit or changes ,so I cant create PR without changes what sould I do ? 


` Showing  with 0 additions and 0 deletions.

No commit comments for this range
` 
I got those messages.After click create new Pull Request.

**Comment by martbhell** [comment] 2021-03-01 08:03
> @hanzei Actually I dont know how can I create WIP PR , I try to create PR but I dont have any commit or changes ,so I cant create PR without changes what sould I do ?
> 
> ` Showing with 0 additions and 0 deletions.
> 
> No commit comments for this range
> `
> I got those messages.After click create new Pull Request.

Are you saying that you are unable to reproduce the issue?

**Comment by hanzei** [comment] 2021-03-01 10:05
@Quaqmre To which branch did you pushed your changes? Did you tried creating the PR via https://github.com/mattermost/mattermost-plugin-gitlab/compare?

**Comment by martbhell** [comment] 2021-04-08 05:46
I can still reproduce this with:

In a private mattermost 5.28.1 channel (and gitlab plugin 1.3.0) I ran:
`/gitlab subscribe johan/dotfiles tag`

Then in my git repo I ran:
```
$ git tag v1.0.7
$ git push origin v1.0.7
Total 0 (delta 0), reused 0 (delta 0)
To mygitlab.example.org:johan/dotfiles.git
 * [new tag]         v1.0.7 -> v1.0.7
 *
$  git push origin --delete v1.0.7
To mygitlab.example.org:johan/dotfiles.git
 - [deleted]         v1.0.7
```

Resulted in these two gitlab notifications:
```
08:42
johan/dotfiles New tag v1.0.7 by : 

08:43

johan/dotfiles New tag v1.0.7 by : 
```

**Comment by DHaussermann** [comment] 2022-01-26 21:01
For this issue - There may value in continuing to deliver the tag deletion events. 

An alternative may simply be to clarify this behavior in the help. @aaronrothschild may have some thoughts here.  
cc @Quaqmre ☝️

**Comment by Kshitij-Katiyar** [comment] 2024-09-02 08:29
@DHaussermann @wiggin77 
I looked into the issue and would like to share my findings.
- The webhook event sent by GitLab in both cases (creation and deletion of a tag) is identical. Unfortunately, no parameter in the webhook payload indicates whether the tag push event is a creation or deletion event.
- One potential solution is to make an additional API call to retrieve the commit data, which might help us differentiate between these types of events.

Please let us know if making an extra API call is a viable approach to resolving this issue and whether we should proceed in this direction.`

**Comment by wiggin77** [comment] 2024-09-03 19:18
> * One potential solution is to make an additional API call to retrieve the commit data, which might help us differentiate between these types of events.

@Kshitij-Katiyar Let's try and see if it works.

**Closed** 2024-11-22 06:43 UTC
Labels: Help Wanted, Hacktoberfest, Difficulty/2:Medium, Good First Issue, Tech/Go, Type/Bug
