### ISSUE TITLE
GitLab produces an error while the webapp is loading - 501 response

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-gitlab#281] opened 2022-03-09 19:47 UTC
When the `flow` branch is deployed, I see GitLab producing an error in the dev console when the web app loads.   
![image](https://user-images.githubusercontent.com/35588783/157520565-75e78d87-ab4a-4fc1-bcfa-1b8555fc038e.png)

**Comment by DHaussermann** [comment] 2022-03-09 19:48
I will isolate this further if there is no quick and obvious cause.

**Comment by hanzei** [comment] 2022-03-09 21:00
1. Is there anything meaningful in the server logs?
2. Does this issue reproduce on `master`?

**Comment by Kshitij-Katiyar** [comment] 2023-09-27 13:17
@DHaussermann @hanzei I was unable to reproduce this issue on `master`. Do you have any extra information for me to reproduce it ?

**Comment by DHaussermann** [comment] 2023-10-02 20:54
It seems like we did not have concrete steps at the time we opened the issue.

0/5 my best guess would be that the connected user may have been in a state where they were not properly authenticated.   

@Kshitij-Katiyar given how old the ticket is, I would close it. We can re-open it with more details if we see it again.

**Comment by Kshitij-Katiyar** [comment] 2023-10-03 08:41
> It seems like we did not have concrete steps at the time we opened the issue.
> 
> 0/5 my best guess would be that the connected user may have been in a state where they were not properly authenticated.
> 
> @Kshitij-Katiyar given how old the ticket is, I would close it. We can re-open it with more details if we see it again.

@DHaussermann sure, I am closing this issue for now.

**Closed by Kshitij-Katiyar** 2023-10-03 08:41 UTC
Labels: Type/Bug
